config/routes.rb
TrackMyTime::Application.routes.draw do
  resource :user_session do 
    get 'logout'
  end
    
  resources :password_resets
  root :controller => 'user_sessions', :action => 'new'
  
  resources :users do
    resources :payments, :only => [:index]
    resources :earnings, :only => [:index]
    resources :time_reports, :only => [:index]
    resources :people
    resources :user_moneys
    resources :calendars, :only => [:index]
    resources :clients do
      member do
        get :projects
      end
    end
    resources :other_projects, :controller => 'other_projects'
    resources :projects do
      member do
        get :toggle_project
        get :toggle_employee
      end
      resources :expenses
      resources :invoices
      resources :project_staffs
      resources :own_hours do
        collection do
          get :start_work
          get :stop_work
          get :cancel_work
        end
      end
      resources :invitations
    end
    resources :notes
  end

  resources :projects, :only => :index do
    resources :employees, :only => :index
  end


  resources :jobs do
    member do
      get :approves
      put :next_state
      put :prev_state
    end
  end

  resources :profiles, :only => [:edit, :update]
  match "/invitations/confirm/:key", :to => "invitations#confirm", :as => "confirm_invitation"
  match "/user-invitations/confirm/:key", :to => "invitations#user_confirm", :as => "user_confirm_invitation"
  
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :noteable, :polymorphic => true 
  validates_presence_of :note
  
  scope :forward,  order('notes.created_at ASC')
  scope :backward, order('notes.created_at DESC')   
end

app/controllers/notes_controller.rb
class NotesController < SecureController
  
  def destroy
    destroy! do |format|
      format.js {}
    end
  end
  
end

app/views/notes/_form.html.haml
= form_for(@note) do |f|
  - if @note.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@note.errors.count, 'error')} prohibited this user from being saved:"
      %ul
      - @note.errors.full_messages.each do |msg|
        %li= msg
  
  .field
    = f.label :noteable_id
    %br
    = f.text_field :noteable_id
  .field
    = f.label :noteable_type
    %br
    = f.text_field :noteable_type
  .field
    = f.label :note
    %br
    = f.text_area :note

  .actions
    = f.submit

app/views/notes/_notes.html.haml
%h2 Notes
.notes
  - noteable.notes.backward.each do |note|
    .note{ :class => cycle(:odd, :even), :id => "note_#{note.id}" }
      .note_date
        .date= note.created_at.to_date.to_s(:short_date)
        .time= note.created_at.to_s(:time_12)
      .message!= RedCloth.new(note.note).to_html
      .controls= link_to 'remove', [current_user, note], :remote => true, :method => :delete, :confirm => 'Are you sure?', :class => 'remove_item_button'
      .clear

= semantic_form_for [current_user, noteable] do |f|
  = f.inputs do
    = f.semantic_fields_for :notes, noteable.notes.build do |form|
      = form.input :note, :input_html => { :rows => '4', :cols => '40' }, :label => 'Add new note'
  = f.buttons do
    = f.submit 'Post'

app/views/notes/destroy.js.haml
==$('#note_#{@note.id}').slideUp();

app/views/notes/edit.html.haml
%h1= t '.title'
%p
  = link_to t('show'), @note
= render 'form'

app/views/notes/index.html.haml
%h1= t('.title')
%p= link_to t('.new_note'), new_note_path

%table
  %thead
    %tr
      %th= Note.human_attribute_name :noteable_id
      %th= Note.human_attribute_name :noteable_type
      %th= Note.human_attribute_name :note
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for note in @notes
      %tr{ :class => cycle(:odd, :even) }
        %td= note.noteable_id
        %td= note.noteable_type
        %td= note.note
        %td.action= link_to t('show'), [current_user, note]
        %td.action= link_to t('edit'), [:edit, current_user, note]
        %td.action= link_to t('destroy'), [current_user, note], :confirm => t('are_you_sure'), :method => :delete

app/views/notes/new.html.haml
%h1= t '.title'
= render 'form'

app/views/notes/show.html.haml
%h1= t '.title'
%p
  = link_to t('edit'), edit_note_path(@note)

%dl
  %dt= Note.human_attribute_name :noteable_id
  %dd= @note.noteable_id
  %dt= Note.human_attribute_name :noteable_type
  %dd= @note.noteable_type
  %dt= Note.human_attribute_name :note
  %dd= @note.note