config/routes.rb
TrackMyTime::Application.routes.draw do
  resource :user_session do 
    get 'logout'
  end
    
  resources :password_resets
  root :controller => 'user_sessions', :action => 'new'
  
  resources :users do
    resources :payments, :only => [:index]
    resources :earnings, :only => [:index]
    resources :time_reports, :only => [:index]
    resources :people
    resources :user_moneys
    resources :calendars, :only => [:index]
    resources :clients do
      member do
        get :projects
      end
    end
    resources :other_projects, :controller => 'other_projects'
    resources :projects do
      member do
        get :toggle_project
        get :toggle_employee
      end
      resources :expenses
      resources :invoices
      resources :project_staffs
      resources :own_hours do
        collection do
          get :start_work
          get :stop_work
          get :cancel_work
        end
      end
      resources :invitations
    end
    resources :notes
  end

  resources :projects, :only => :index do
    resources :employees, :only => :index
  end


  resources :jobs do
    member do
      get :approves
      put :next_state
      put :prev_state
    end
  end

  resources :profiles, :only => [:edit, :update]
  match "/invitations/confirm/:key", :to => "invitations#confirm", :as => "confirm_invitation"
  match "/user-invitations/confirm/:key", :to => "invitations#user_confirm", :as => "user_confirm_invitation"
  
end

app/controllers/employees_controller.rb
class EmployeesController < SecureController
  def index
    @project = current_user.projects.find params[:project_id]
    #@employees = current_user.projects.find(params[:project_id]).people
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/index.html.haml
= content_for :on_ready do
  :plain
    $(".cb").live("change", function() {
      link = $(this).parents(".person").find(".remove_item_button:first");
      href = link.attr("href");
      $.ajax({url: href});
    });

%h2.left== Manage Employees on #{@project.title}
.right.add= link_to 'Back to Project', [current_user, @project], :class => 'show_button'
.clear

.staff
  -# if @project.project_staffs.count > 0
  - if current_user.people.count > 0
    .person
      .checkbox
        &nbsp;
      .full_person_name 
        %strong Person
      .rate
        %strong Hourly Rate
      .full_hours_count
        %strong Hours
      .amount
        %strong Total
      .person_name.none
        %strong Actions
      .clear  
    - current_user.people.by_name.each do |person|
      - staff = @project.project_staffs.by_person(person.id).first
      .person{ :class => cycle(:odd, :even), :id => "staff-#{person.id}" }
        .checkbox
          = check_box_tag :user_id, 'checked', @project.project_staffs.by_person(person.id).any?, :class => 'cb'
        .full_person_name= link_to person.name, [current_user, person]
        .rate
          - rate = staff.present? ? staff.hourly_rate : person.hourly_rate
          = rate.present? ? "#{number_to_currency(rate)} / h" : '-'
        .full_hours_count= person.total_hours_on @project
        .amount= number_to_currency(person.total_money_on(@project), :precision => 2)
        .person_name.none= link_to 'remove from project', toggle_employee_user_project_path(current_user, @project, :person_id => person), :remote => true, :class => 'remove_item_button'
        .clear
  - else
    .staff_list_is_empty
      %i List is empty. First try to add employee.