config/routes.rb
TrackMyTime::Application.routes.draw do
  resource :user_session do 
    get 'logout'
  end
    
  resources :password_resets
  root :controller => 'user_sessions', :action => 'new'
  
  resources :users do
    resources :payments, :only => [:index]
    resources :earnings, :only => [:index]
    resources :time_reports, :only => [:index]
    resources :people
    resources :user_moneys
    resources :calendars, :only => [:index]
    resources :clients do
      member do
        get :projects
      end
    end
    resources :other_projects, :controller => 'other_projects'
    resources :projects do
      member do
        get :toggle_project
        get :toggle_employee
      end
      resources :expenses
      resources :invoices
      resources :project_staffs
      resources :own_hours do
        collection do
          get :start_work
          get :stop_work
          get :cancel_work
        end
      end
      resources :invitations
    end
    resources :notes
  end

  resources :projects, :only => :index do
    resources :employees, :only => :index
  end


  resources :jobs do
    member do
      get :approves
      put :next_state
      put :prev_state
    end
  end

  resources :profiles, :only => [:edit, :update]
  match "/invitations/confirm/:key", :to => "invitations#confirm", :as => "confirm_invitation"
  match "/user-invitations/confirm/:key", :to => "invitations#user_confirm", :as => "user_confirm_invitation"
  
end

app/controllers/other_projects_controller.rb
class OtherProjectsController < SecureController
  helper_method :sort_column, :sort_direction
  
  def index
    @projects = (current_user.other_projects_with_history + current_user.other_projects).uniq
  end

  def show
    @project = current_user.other_projects.find_by_id params[:id]
    @project = current_user.other_projects_with_history.find_by_id params[:id] unless @project
  end

end

app/views/other_projects/index.html.haml
%h1.left.no_bottom_margin.margin_bottom_30px.margin_top_1em Projects
.clear
- if @projects.any?
  #other_projects_container
    %table.zebra
      %thead
        %tr
          %th ID
          %th Project Name
          %th Status
          %th Total Hours
          %th Amount
          %th Pending & Approved
          %th Actions
      %tbody
        - @projects.each do |project|
          %tr
            %td= link_to project.ui_title, user_other_project_path(current_user, project)
            %td= link_to project.title, user_other_project_path(current_user, project)
            %td= project.project_status
            %td= number_with_delimiter project.employee_hours_total(current_user), :precision => 2
            %td= number_to_currency(project.amount_total(current_user), :precision => 2)
            %td= number_to_currency(project.amount_pending(current_user) + project.amount_approved(current_user), :precision => 2)
            %td
              - staff = project.project_staffs.by_person(current_user.id).first
              = link_to (staff.present? ? "Log Work" : "Details"), user_other_project_path(current_user, project)

app/views/other_projects/show.html.haml
%h1.left.no_bottom_margin.margin_bottom_30px.margin_top_1em== #{@project.title} (#{@project.project_status})
.add.right= link_to 'Back', [current_user, :other_projects], :class => 'list_button'
.clear

%p= @project.description

- staff = @project.project_staffs.by_person(current_user.id).first
- if staff
  %p Your Rate: #{number_to_currency staff.hourly_rate}

.staff.jobs
  .person
    .person_description
      %strong Description
    .hours_count
      %strong Hours
    .amount
      %strong Money
    .amount
      %strong Added on
    .state
      %strong State
    .controls
      %strong Actions
    .clear
  = render :partial => 'jobs/persons_job', :collection => @project.jobs_by(current_user), :as => :job

- if staff
  = render 'jobs/form', :user => current_user, :project => @project